spring.application.name=wetPolicies

# Conf para banco local (H2 em memoria local local)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.messages.basename=messages

# Ativar a validacao JSR-303/JSR-349/JSR-380
spring.web.locale=pt_BR

spring.messages.encoding=UTF-8

spring.security.oauth2.client.registration.github.client-id=Ov23lievS1J0gImki5Bw
spring.security.oauth2.client.registration.github.client-secret=5cfcee4444ba0ab1307b2a6504d0b3c2f39bf105

spring.security.oauth2.client.registration.google.client-id=adicionar
spring.security.oauth2.client.registration.google.client-secret=adicionar

logging.level.org.springframework.jdbc.datasource.DataSourceUtils=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration=DEBUG
